[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.2"
rayon = "1.7.0"
wgpu = "0.15.1"
rand = "0.8.5"
image = "0.24.6"
chrono = "0.4.24"
