[camera]
lookfrom = [ 13.0, 2.0, 3.0 ]
lookat = [ 0.0, 0.0, 0.0 ]
vup = [ 0.0, 1.0, 0.0 ]
vfov = 20.0
aspect_ratio = 1.5
aperture = 0.1
focus_distance = 10.0

[image]
samples_per_pixel = 100
max_depth = 15
width = 800

[viewport]
pixel_batch_size = 200_000
window_scale = 1
